/* Aurora — cyberpunk / dark: single source for all CSS custom properties. */

const c = {
  /* Reference canvas */
  pageBg: "#0a0a0f",
  cardTop: "#0e1018",
  cardBottom: "#0a0b12",
  railStart: "#060712",
  railEnd: "#0a0c14",
  border: "rgba(255, 255, 255, 0.1)",
  borderStrong: "rgba(255, 255, 255, 0.12)",
  textPrimary: "#ffffff",
  textMuted: "#9ca3af",
  accentCyan: "#3b82f6",
  accentPurple: "#8b5cf6",
  /* Reference --status-success */
  success: "#10b981",
  warning: "#3b82f6",
  pending: "#64748b",
  error: "#f87171",
  onPrimary: "#ffffff",

  brand: "#a5b4fc",
  topbarEm: "#e2e8f0",
  topbarSub: "#94a3b8",
  topbarIconBorder: "rgba(255, 255, 255, 0.12)",
  topbarIcon: "#c4d0f0",

  railLogo: "#b8f0ff",
  railLogoRing: "rgba(64, 224, 255, 0.5)",
  railBtn: "rgba(255, 255, 255, 0.04)",
  railBtnText: "#a8b6cc",
  railActiveText: "#f1f5f9",
  railActiveA: "rgba(139, 92, 246, 0.25)",
  railActiveB: "rgba(64, 224, 255, 0.08)",

  systemCardBorder: "rgba(255, 255, 255, 0.08)",
  systemCardSurface: "rgba(5, 8, 14, 0.65)",
  systemCardHeading: "#94a3b8",
  /** CPU activity spark (sidebar) */
  systemSparkStroke: "#22c55e",
  statTrack: "rgba(255, 255, 255, 0.08)",

  statCpu: "linear-gradient(90deg, #40e0ff, #2dd4bf)",
  statRam: "linear-gradient(90deg, #8b5cf6, #a78bfa)",
  statGpu: "linear-gradient(90deg, #f59e0b, #f97316)",
  statNpu: "linear-gradient(90deg, #ec4899, #f472b6)",

  /* Voice status dot (Ready — reference) */
  voiceReadyDot: "#00c853",
  voiceLive: "#00c853",
  voiceWaveA: "rgba(64, 201, 255, 0)",
  /* Pixel reference: cyan → electric purple orbits */
  voiceWaveB: "#40c9ff",
  voiceWaveC: "#9747ff",
  voiceOrbitCyan: "#40c9ff",
  voiceOrbitPurple: "#9747ff",
  voiceCardBg: "#0c0d14",
  /** Panel lift — separate from generic cards */
  voiceCardShadow:
    "0 1px 0 rgba(255, 255, 255, 0.04) inset, 0 28px 56px rgba(0, 0, 0, 0.55), 0 0 0 1px rgba(255, 255, 255, 0.06)",
  voiceWaveLineGlow: "0 0 10px rgba(64, 201, 255, 0.22)",
  audioBarOnGlow: "0 0 6px rgba(64, 201, 255, 0.28)",
  voiceOutPanel: "#11141d",
  voiceIconMuted: "#94a3b8",
  voiceStopGrad: "linear-gradient(135deg, #40c9ff 0%, #9747ff 100%)",
  voiceRing:
    "radial-gradient(circle at 35% 32%, rgba(64, 201, 255, 0.42), transparent 42%), radial-gradient(circle at 72% 68%, rgba(151, 71, 255, 0.4), transparent 48%), conic-gradient(from 215deg, #40c9ff, #6b5cf6, #9747ff, #c084fc, #40c9ff)",
  voiceDial: "#0a0b12",
  voiceDialBorder: "rgba(64, 201, 255, 0.32)",
  voiceBtnBorder: "rgba(255, 255, 255, 0.1)",
  voiceBtn: "rgba(255, 255, 255, 0.05)",
  voiceBtnText: "#e2e8f0",
  voiceMeta: "#8b9bb4",
  voiceOutSurface: "#11141d",
  voiceOutBorder: "rgba(255, 255, 255, 0.08)",

  audioIdle: "rgba(148, 163, 184, 0.2)",
  audioOn: "linear-gradient(180deg, #40c9ff, #7c5cff)",

  thinkingBorder: "rgba(255, 255, 255, 0.06)",
  thinkingSurface: "rgba(5, 8, 14, 0.45)",
  thinkingMeta: "#8b9bb4",
  emDone: "#4ade80",
  emRun: "#60a5fa",
  emPending: "#94a3b8",

  bubbleBorder: "rgba(255, 255, 255, 0.08)",
  bubble: "rgba(8, 12, 22, 0.8)",
  bubbleUser: "rgba(139, 92, 246, 0.35)",
  bubbleAssistant: "rgba(64, 224, 255, 0.2)",
  bubbleLabel: "#a5b4fc",
  inputText: "#e8ecf4",
  inputSurface: "rgba(5, 8, 14, 0.7)",
  composerTool: "rgba(255, 255, 255, 0.05)",
  memoryText: "#cbd5e1",
  memoryTitle: "#94a3b8",
  activityBorder: "rgba(255, 255, 255, 0.06)",

  footerBg: "rgba(5, 8, 14, 0.85)",
  footerBorder: "rgba(255, 255, 255, 0.08)",
  footerSuccess: "#10b981",

  railDevTrack: "rgba(255, 255, 255, 0.1)",
  railDevOn: "#40e0ff",
  railDevOutline: "rgba(16, 185, 129, 0.28)",

  /** TopBar profile chip glow (no raw rgba in components) */
  topAvatarGlow: "0 0 16px rgba(59, 130, 246, 0.35)",

  statGlowCpu: "0 0 8px rgba(64, 224, 255, 0.3)",
  statGlowRam: "0 0 8px rgba(139, 92, 246, 0.3)",
  statGlowGpu: "0 0 8px rgba(245, 158, 11, 0.3)",
  statGlowNpu: "0 0 8px rgba(236, 72, 153, 0.3)",
  railToggleOnBg: "rgba(64, 224, 255, 0.15)",
  composerSendGlow: "0 0 16px rgba(59, 130, 246, 0.25)",
  /** Chat composer — prominent purple mic (ref) */
  composerMicGrad: "linear-gradient(145deg, #6d28d9, #8b5cf6, #a78bfa)",
  composerMicGlow: "0 0 20px rgba(139, 92, 246, 0.55), 0 0 0 1px rgba(255, 255, 255, 0.08) inset",
  bubbleUserFill: "rgba(139, 92, 246, 0.1)",
  bubbleAsstFill: "rgba(59, 130, 246, 0.08)",
  bubbleUserGradientEnd: "#6d28d9",
} as const;

const effect = {
  cardShadow: "0 1px 0 rgba(255, 255, 255, 0.04) inset, 0 20px 40px rgba(0, 0, 0, 0.45), 0 0 0 1px rgba(255, 255, 255, 0.03)",
  railLogo: "0 0 0 1px var(--c-rail-logo-ring), 0 0 24px rgba(64, 224, 255, 0.45)",
  voiceLiveGlow: "0 0 12px var(--c-voice-live)",
  voiceRingShadow: "0 0 48px rgba(151, 71, 255, 0.38), 0 0 64px rgba(64, 201, 255, 0.22)",
  stopBtn:
    "0 0 0 2px rgba(139, 92, 246, 0.45), 0 0 0 3px rgba(64, 201, 255, 0.22), 0 0 28px rgba(151, 71, 255, 0.5), 0 0 44px rgba(64, 201, 255, 0.32)",
  waveLine: `linear-gradient(90deg, ${c.voiceWaveA}, ${c.voiceWaveB}, ${c.voiceWaveC}, ${c.voiceWaveA})`,
} as const;

const bodyGlowA = "rgba(64, 224, 255, 0.12)";
const bodyGlowB = "rgba(139, 92, 246, 0.1)";
const bodyBackground = [
  `radial-gradient(1000px 800px at 20% 0%, ${bodyGlowA}, transparent 55%)`,
  `radial-gradient(900px 600px at 90% 20%, ${bodyGlowB}, transparent 50%)`,
  c.pageBg,
].join(", ");

const layout = {
  railW: "208px",
  dashboardPad: "20px 24px 0",
  contentGap: "20px",
  rightCol: "minmax(300px, 380px)",
  centerMin: "0",
  topbarMb: "20px",
  topIcon: "40px",
  topIconGap: "12px",
  cardRadius: "14px",
  cardPad: "20px",
  /** Voice panel (reference ~12px cards) */
  voiceCardRadius: "14px",
  voiceOutRadius: "12px",
  voiceRingOuter: "200px",
  voiceRingInner: "128px",
  voiceOutCol: "minmax(220px, 280px)",
} as const;

const railActiveBg = `linear-gradient(90deg, ${c.railActiveA}, ${c.railActiveB})`;
const statGradient = c.statCpu; /* default for legacy; per-row uses --c-stat-*-grad */

export const theme = { colors: c, effect, layout, body: { bodyBackground } } as const;

export const themeVars: Record<string, string> = (() => {
  const m: Record<string, string> = {
    "--c-page-bg": c.pageBg,
    "--c-rail-start": c.railStart,
    "--c-rail-end": c.railEnd,
    "--c-border": c.border,
    "--c-border-strong": c.borderStrong,
    "--c-text": c.textPrimary,
    "--c-muted": c.textMuted,
    "--c-accent-cyan": c.accentCyan,
    "--c-accent-blue": c.accentCyan,
    "--c-accent-purple": c.accentPurple,
    "--c-success": c.success,
    "--c-warning": c.warning,
    "--c-pending": c.pending,
    "--c-error": c.error,
    "--c-on-primary": c.onPrimary,
    "--c-card-top": c.cardTop,
    "--c-card-bottom": c.cardBottom,
    "--c-brand": c.brand,
    "--c-topbar-title": c.topbarEm,
    "--c-topbar-sub": c.topbarSub,
    "--c-topbar-icon-border": c.topbarIconBorder,
    "--c-topbar-icon": c.topbarIcon,
    "--c-rail-logo": c.railLogo,
    "--c-rail-logo-border": c.railLogoRing,
    "--c-rail-logo-ring": c.railLogoRing,
    "--c-rail-btn": c.railBtn,
    "--c-rail-btn-text": c.railBtnText,
    "--c-rail-active-text": c.railActiveText,
    "--c-rail-active-a": c.railActiveA,
    "--c-rail-active-b": c.railActiveB,
    "--c-rail-active-bg": railActiveBg,
    "--c-system-border": c.systemCardBorder,
    "--c-system-surface": c.systemCardSurface,
    "--c-system-heading": c.systemCardHeading,
    "--c-stat-track": c.statTrack,
    "--c-system-spark-stroke": c.systemSparkStroke,
    "--c-stat-start": c.accentCyan,
    "--c-stat-end": c.accentPurple,
    "--c-stat-gradient": statGradient,
    "--c-stat-cpu": c.statCpu,
    "--c-stat-ram": c.statRam,
    "--c-stat-gpu": c.statGpu,
    "--c-stat-npu": c.statNpu,
    "--c-voice-live": c.voiceLive,
    "--c-voice-dot-shadow": effect.voiceLiveGlow,
    "--c-voice-wave": effect.waveLine,
    "--c-voice-ring": c.voiceRing,
    "--c-voice-dial": c.voiceDial,
    "--c-voice-dial-border": c.voiceDialBorder,
    "--c-voice-btn-border": c.voiceBtnBorder,
    "--c-voice-btn": c.voiceBtn,
    "--c-voice-btn-text": c.voiceBtnText,
    "--c-voice-meta": c.voiceMeta,
    "--c-voice-out-surface": c.voiceOutSurface,
    "--c-voice-out-border": c.voiceOutBorder,
    "--c-voice-card-bg": c.voiceCardBg,
    "--c-voice-card-shadow": c.voiceCardShadow,
    "--c-voice-wave-line-glow": c.voiceWaveLineGlow,
    "--c-audio-bar-on-glow": c.audioBarOnGlow,
    "--c-voice-icon-muted": c.voiceIconMuted,
    "--c-voice-stop-grad": c.voiceStopGrad,
    "--c-voice-orbit-cyan": c.voiceOrbitCyan,
    "--c-voice-orbit-purple": c.voiceOrbitPurple,
    "--c-audio-idle": c.audioIdle,
    "--c-audio-on": c.audioOn,
    "--c-thinking-border": c.thinkingBorder,
    "--c-thinking-surface": c.thinkingSurface,
    "--c-thinking-meta": c.thinkingMeta,
    "--c-em-done": c.emDone,
    "--c-em-run": c.emRun,
    "--c-em-pending": c.emPending,
    "--c-bubble-border": c.bubbleBorder,
    "--c-bubble": c.bubble,
    "--c-bubble-user": c.bubbleUser,
    "--c-bubble-assistant": c.bubbleAssistant,
    "--c-bubble-label": c.bubbleLabel,
    "--c-input": c.inputText,
    "--c-input-surface": c.inputSurface,
    "--c-composer-tool-border": c.borderStrong,
    "--c-composer-tool": c.composerTool,
    "--c-memory": c.memoryText,
    "--c-memory-title": c.memoryTitle,
    "--c-activity-border": c.activityBorder,
    "--c-activity-meta": c.textMuted,
    "--c-body-bg": bodyBackground,
    "--c-shadow-card": effect.cardShadow,
    "--c-shadow-rail-logo": effect.railLogo,
    "--c-shadow-voice-glow": effect.voiceRingShadow,
    "--c-shadow-stop": effect.stopBtn,
    "--c-footer-bg": c.footerBg,
    "--c-footer-border": c.footerBorder,
    "--c-footer-ok": c.footerSuccess,
    "--c-rail-dev-track": c.railDevTrack,
    "--c-rail-dev-on": c.railDevOn,
    "--c-rail-dev-outline": c.railDevOutline,
    "--c-top-avatar-glow": c.topAvatarGlow,
    "--c-stat-glow-cpu": c.statGlowCpu,
    "--c-stat-glow-ram": c.statGlowRam,
    "--c-stat-glow-gpu": c.statGlowGpu,
    "--c-stat-glow-npu": c.statGlowNpu,
    "--c-rail-toggle-on-bg": c.railToggleOnBg,
    "--c-composer-send-glow": c.composerSendGlow,
    "--c-composer-mic-grad": c.composerMicGrad,
    "--c-composer-mic-glow": c.composerMicGlow,
    "--c-bubble-user-fill": c.bubbleUserFill,
    "--c-bubble-asst-fill": c.bubbleAsstFill,
    "--c-bubble-user-grad-end": c.bubbleUserGradientEnd,
    "--layout-rail-w": layout.railW,
    "--layout-dashboard-pad": layout.dashboardPad,
    "--layout-content-gap": layout.contentGap,
    "--layout-right-col": layout.rightCol,
    "--layout-center-min": layout.centerMin,
    "--layout-topbar-mb": layout.topbarMb,
    "--layout-top-icon": layout.topIcon,
    "--layout-top-icon-gap": layout.topIconGap,
    "--layout-card-radius": layout.cardRadius,
    "--layout-card-pad": layout.cardPad,
    "--layout-voice-card-radius": layout.voiceCardRadius,
    "--layout-voice-out-radius": layout.voiceOutRadius,
    "--layout-voice-ring-outer": layout.voiceRingOuter,
    "--layout-voice-ring-inner": layout.voiceRingInner,
    "--layout-voice-out-col": layout.voiceOutCol,
  };
  return m;
})();

export function applyThemeToDocument() {
  const root = document.documentElement;
  for (const [k, v] of Object.entries(themeVars)) {
    root.style.setProperty(k, v);
  }
}
